### PR TITLE
add: glimmerx support

### PR DESCRIPTION
**Pull request by lifeart**
## Links: 

GlimmerX: https://github.com/glimmerjs/glimmer-experimental
Vite plugin GlimmerX: https://github.com/lifeart/vite-plugin-glimmerx

### CODE REVIEW

**Comment by IanVS** [comment]
Hi, there doesn't seem to be a `glimmerx` storybook framework, from what I can tell, so I don't think this will have the intended effect.  Can you please explain what you are wanting to accomplish?  Are you able to use glimmerx with the standard storybook (without vite)?

**Comment by lifeart** [comment]
Hi @IanVS, it is: https://github.com/glimmerjs/glimmer-experimental/tree/master/packages/%40glimmerx/storybook

**Review by IanVS — APPROVED** [review]
Seems okay to me, and I think it's okay not to have an example app in this repo since it sounds like glimmerx is experimental.

**Comment by lifeart** [comment]
@IanVS thank you! Let me know if example app is required, I could add it.

**Comment by lifeart** [comment]
@IanVS thank you!

**Pull request merged**
