### PR TITLE
Improving maintainability: run `lint`

### PR DESCRIPTION
**Pull request by mrauhu**
Hello.

This pull request is part of https://github.com/eirslett/storybook-builder-vite/issues/188.

Resolves https://github.com/eirslett/storybook-builder-vite/pull/193#issuecomment-1006256729.

Done:

- [x] Run `lint` on all codebase.
- [x] Fix code inspection warnings from a JetBrains IDE for the `packages/storybook-builder-vite` directory.
- [x] Create `.git-blame-ignore-revs` file.

@eirslett, @IanVS 

For setup, run once:

```
git config blame.ignoreRevsFile .git-blame-ignore-revs
```

Also, you can enable the `Hide whitespace changes` option in the `Files changed` tab settings.

Best wishes,
Sergey.

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks for this, I will review it after #193 is merged, since it is difficult right now to tell what's a part of this PR and what's a part of the other.

**Comment by mrauhu** [comment]
Rebased onto `main` branch.

**Comment by IanVS** [comment]
We will need to change the SHA in `.git-blame-ignore-revs` now, since this was squash-merged.

**Comment by mrauhu** [comment]
> We will need to change the SHA in `.git-blame-ignore-revs` now, since this was squash-merged.

@IanVS fixed in #198.

**Pull request merged**
