### PR TITLE
Upgrade to storybook/csf-tools for MDX processing

### PR DESCRIPTION
**Pull request by shilman**
## What I did

Use `@storybook/csf-tools` for MDX compilation to avoid large dependency on `@storybook/addon-docs`, per request by @TheComputerM 

## How to test

I'm not sure. Basically the latest RC of Storybook breaks vite-builder-storybook because addon-docs dist file no longer exists in RC.3. So we need to publish the builder and then update the examples to use 0.0.8.

### CODE REVIEW

**Comment by eirslett** [comment]
It should be possible to test locally in this repo - it symlinks node_modules so that you can run the example project with the local version of the builder.

**Comment by IanVS** [comment]
I have not found this to be the case so far.  npm is using version 0.0.7 from the registry inside the example packages.  I can't figure out how to get it to properly symlink to the pacakge on disk.

**Comment by eirslett** [comment]
If you delete the node_modules inside each subproject (they should be empty, expect for .cache folders inside them maybe), all the subprojects should get their dependencies from the node_modules folder in the root directory. (If you run npm install in the root directory, it will install all dependencies from the sub-packages as well)

**Comment by eirslett** [comment]
If you find a better way (use yarn or lerna maybe), we could switch. This project uses npm workspaces today, but that was an arbitrary choice.

**Comment by IanVS** [comment]
I think the workspace support in yarn is much more mature, and is what the core storybook monorepo uses, so I might take a crack moving us over to that if you don't mind.  If anything, storybook contributors might be more used to running yarn and it might be easier for them to contribute here as well.  But I'll keep trying to test this out in the meantime.

**Comment by TheComputerM** [comment]
> If you find a better way (use yarn or lerna maybe), we could switch. This project uses npm workspaces today, but that was an arbitrary choice.

PNPM is the best for monorepos, I highly recommend it.

**Comment by TheComputerM** [comment]
Thank you very much @shilman

**Comment by IanVS** [comment]
>PNPM is the best for monorepos, I highly recommend it.

I'm interested in pnpm, it looks very cool, but I think it makes sense to stick to the tooling that the main storybook monorepo uses, which is yarn.  This way it's easier for contributors to jump between projects.

**Pull request merged**
