### PR TITLE
Improving maintainability: TypeScript

### PR DESCRIPTION
**Pull request by mrauhu**
Hello.

This pull request is part of #188.

Done:

- [x] Use TypeScript (with right `tsconfig.json` for comfort debugging).
- [x] Convert all codebase from `*.js` to `*.ts`.
- [x] Typization.

@eirslett, @IanVS 

Best wishes,
Sergey.

### CODE REVIEW

**Comment by eirslett** [comment]
What if we set `indent_size = 4` in `.editorconfig`? That's the current code style of the project (I think... even if it's different in some places?) and might lead to fewer lines changed in the commit diff.

**Comment by mrauhu** [comment]
> indent_size = 4

@eirslett It feels like PHP for me, so I changed it to the Prettier.

**Comment by mrauhu** [comment]
> ...  and might lead to fewer lines changed in the commit diff.

image

@eirslett In the Files changed tab, please, check the Hide whitespace option and then click to the Apply and Reload button.

**Comment by mrauhu** [comment]
@eirslett, @IanVS 

I converted the `storybook-builder-vite` code from JavaScript to TypeScript with [`strict`](https://www.typescriptlang.org/tsconfig#strict) flag enabled and fixed found bugs.

Also I made a small optimization to remove a duplicated code in the 7e73d0b commit.
It's inspired by #182 pull request, but as far I know there is no breaking changes.

This pull requests includes #193 and #196, so you need merge them first.

If you want to see diffs between them, you can use these links:

1. #193
  * https://github.com/eirslett/storybook-builder-vite/pull/193/files?diff=split&w=1
2. #196 
  * Run `lint` on all codebase.
  https://github.com/eirslett/storybook-builder-vite/pull/196/files/fdd592ef8e8b7843bd8756e0356c3df949b83fd6..929215d73c66dbec669ff3dd964c01530ed36286?diff=split&w=1
  * Fix code inspection warnings from a JetBrains IDE for the `packages/storybook-builder-vite` directory.
https://github.com/eirslett/storybook-builder-vite/pull/196/files/929215d73c66dbec669ff3dd964c01530ed36286..a8a5be0ca607fdea5051054ff9cdcec1213b668d?diff=split&w=1
3. #195 
  * Convert all codebase from `*.js` to `*.ts`.
  https://github.com/eirslett/storybook-builder-vite/pull/195/files/a81127990c1b1153b3e8a0db636a15706d1d2ee6..e3f404510a552cedf10c9281dec9f5c211fb83e1
  * Typization.
  https://github.com/eirslett/storybook-builder-vite/pull/195/files/e3f404510a552cedf10c9281dec9f5c211fb83e1..7e73d0be7dfe61e76ff9b3f638c9ab33edfd7e56

**Comment by mrauhu** [comment]
Rebased onto #196.

**Comment by eirslett** [comment]
Looks like it's in a conflict state after merging #196 ...

**Comment by mrauhu** [comment]
> Looks like it's in a conflict state after merging #196 ...

@eirslett Fixed it.

This is most likely caused by squash merging. 
If we have multiple branches on top of each other then it is better to use the Rebase and merge method.

**Comment by eirslett** [comment]
Super, thanks a lot! Now we're in TypeScript land!

**Pull request merged**
