### PR TITLE
Add build examples workflow

### PR DESCRIPTION
**Pull request by rqbazan**
### Context

Please read https://github.com/eirslett/storybook-builder-vite/issues/31

### Changes

My very first idea was to add a new step in the current `Build and Publish to NPM` workflow in order to build all the [examples packages](https://github.com/eirslett/storybook-builder-vite/tree/3abcdd1d4cd1c3f82f23e3e636c4716fbe55765e/packages). However, I've decided to create a new workflow because the build examples step must run three times, one for each operative system, so this behavior isn't properly along with a publish step.

### CODE REVIEW

**Comment by IanVS** [comment]
It seems there's a problem running the actions:

```
GitHub Actions has encountered an internal error when running your job.
```

**Comment by rqbazan** [comment]
Hey @IanVS, please re-run

**Comment by eirslett** [comment]
Looks like it fails on Windows! Maybe something with `/` vs `\` in file paths?

**Comment by rqbazan** [comment]
Hey @eirslett,

That's sounds right because the error message shows a relative path but it seems unrecognizable by the build process. 🤔 

```node
 ERR! Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../../../../../iframe.html".
```

**Comment by IanVS** [comment]
I think this properly reproduces the issue in https://github.com/eirslett/storybook-builder-vite/issues/31, and adds value to our build process.  We (or someone!) will need to spend some work to fix the windows issue, but at least now we'll have a reminder that it's broken and a good way to check if it's fixed.  Thanks @rqbazan!

**Pull request merged**
