### PR TITLE
Add synchronous-promise as optimized dependencies

### LINKED ISSUE #134: non esm-module synchronous-promise causes unexpected error
The error shows as below

```
The requested module '/node_modules/synchronous-promise/index.js?v=65ef6137' does not provide an export named 'SynchronousPromise'
```
Seems like synchronous-promise hasn't been added to vite config `optimizeDeps.include`, I'll make a pr to fix this.

### PR DESCRIPTION
**Pull request by razor1895**
closes #134

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks, do you know what part of storybook this is being pulled in from?

**Comment by upupming** [comment]
Same problem here, solved by add to viteFinal: https://github.com/upupming/vue3-compact-template/blob/main/.storybook/main.js#L26

**Comment by razor1895** [comment]
@IanVS the changed were made a few days ago https://github.com/storybookjs/storybook/pull/16517/files#diff-9ef4b08eac91bf0736147d461adb5e08865fd311b041615e6aae5f2ec47753e1R15

**Comment by IanVS** [comment]
Cool, thanks for tracking that down, and for the PR!

**Comment by razor1895** [comment]
@IanVS It's my pleasure

**Pull request merged**
