### PR TITLE
Test built storybooks in CI

### PR DESCRIPTION
**Pull request by IanVS**
So far, we've only been building our storybooks, but not doing any testing on them.  This adds https://github.com/storybookjs/test-runner which will render each of the stories and smoke test them (make sure that there are no runtime errors).  This is at least a step towards having more confidence that our stories aren't broken.  The next step would be to actually write assertions in the stories to be sure they're rendering _correctly_, but that can be done another time.

### CODE REVIEW

**Comment by IanVS** [comment]
The svelte stories are not being picked up correctly by the test runner.  I've opened https://github.com/storybookjs/test-runner/issues/80.

**Comment by IanVS** [comment]
Hmmm, there seem to be other issues in vue and svelte for the alpha versions, which I'll need to investigate later.

**Comment by IanVS** [comment]
I had to remove the svelte example, unfortunately.  It seems that @storybook/test-runner does not support svelte component stories.

**Comment by eirslett** [comment]
LGTM!

**Pull request merged**
